FROM eclipse-temurin

LABEL mentainer="dhruv@gmail.com"

WORKDIR /app

COPY  target/employee-service-0.0.1-SNAPSHOT.jar /app/springboot-employee-service.jar

CMD ["java", "-jar", "springboot-employee-service.jar"]