FROM eclipse-temurin

LABEL mentainer="dhruv@gmail.com"

WORKDIR /app

COPY  target/service-registry-0.0.1-SNAPSHOT.jar /app/springboot-service-registry.jar

CMD ["java", "-jar", "springboot-service-registry.jar"]