FROM eclipse-temurin

LABEL mentainer="dhruv@gmail.com"

WORKDIR /app

COPY  target/department-service-0.0.1-SNAPSHOT.jar /app/springboot-department-service.jar

CMD ["java", "-jar", "springboot-department-service.jar"]